### ISSUE TITLE
Diagram DTSLS

### ISSUE THREAD

**Issue by drewyoungren** [rbeezer/fcla#69]
The decision tree diagram does not show up (for me) here: https://books.aimath.org/fcla/section-TSS.html

![image](https://cloud.githubusercontent.com/assets/19934878/22377180/e0e77ce2-e47e-11e6-9448-447aaeca4ec8.png)

I do see it in the version hosted at linear.ups.edu.

**Comment by rbeezer** [comment]
Thanks very much, Drew.  I've sent details on to David Farmer and we'll 
coordinate on a fix.

Since this is more about AIM setup, and not FCLA proper, might be best to alert 
the "sage-utmost-testsite" group (I'll put a notice there now).  No problem, and 
thanks for all the quick accurate reports.

Rob

**Comment by rbeezer** [comment]
Diagrams in FCLA should all be working fine now.  **Everything** should be working better.

Thanks again for the report.
